name: github-actions-cicd-demo
on:
  push:
    branches:
      - '*'
permissions:
  contents: read
jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: 'Start Build Job'
        run: |
          echo "Starting the build job."
      - name: 'Checkout'
        uses: actions/checkout@v4.1.1
      - name: 'Setup Java JDK'
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: 'Get Version Number'
        run: |
            echo "VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')" >> $GITHUB_ENV
      - name: 'Publish JAR'
        uses: actions/upload-artifact@v3.1.3
        with:
          name: 'micronaut-cicd-demo-${{env.VERSION}}-all.jar'
          path: build/libs/*-all.jar
      - name: 'Check Java Version'
        run: |
          java --version
      - name: 'Assemble JAR'
        run: |
          ./gradlew assemble
      
      
